@startuml
left to right direction
actor ユーザー
actor 管理者
rectangle ショッピングサイト{
	ユーザー --> (ログインログアウト)
	ユーザー --> (商品検索・閲覧)
	ユーザー --> (商品購入)
	ユーザー --> (レビュー閲覧・投稿)
	管理者 --> (商品掲載)
	管理者 --> (レビュー閲覧・投稿)
	管理者 --> (商品管理)
	管理者 --> (ログインログアウト)
	}
	管理者 --> (アカウント管理)
@enduml